name: Project Template
about: Template for new projects
description: Fill in information to initialize your project

# Inputs to ask
inputs:
  project_name:
    description: "Name of the new project"
    required: true
    default: "my-project"
  author:
    description: "Author of the project"
    required: true
    default: "Anonymous"
  license:
    description: "Choose a license"
    required: true
    default: "MIT"
