repos:
  - repo: local
    hooks:
      # disable make-test for now, as it is too slow
      # - id: make-test
      #   name: Run Make test
      #   entry: make run-tests-py
      #   language: system
      #   files: "^.*"   # only run if files under api/ changed
      #   stages: [] 

      - id: isort
        name: Run isort on API
        entry: isort .
        language: system
        files: '^.*\.py$'

      - id: black
        name: Run Black on API
        entry: black
        language: system
        files: '^.*\.py$'

      - id: lint
        name: Run pylint on API
        entry: make lint
        language: system
        files: "^.*"
