name: Initialize Project

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run setup script
        run: |
          chmod +x scripts/setup.sh
          ./scripts/setup.sh
